static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: upstream
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: upstream-service
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config: 
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                auth0:
                  issuer: https://take0a.jp.auth0.com/
                  audiences:
                  - https://zenn.dev/take0a
                  remote_jwks:
                    http_uri:
                      uri: https://take0a.jp.auth0.com/.well-known/jwks.json
                      cluster: take0a.jp.auth0.com|443
                      timeout: 5s
                    cache_duration:
                      seconds: 300
                  payload_in_metadata: jwt_payload
              rules:
              - match:
                  prefix: "/"
                requires:
                  provider_name: auth0
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              default_source_code:
                inline_string: |
                  function envoy_on_request(request_handle)
                    local meta = request_handle:streamInfo():dynamicMetadata()
                    for key, value in pairs(meta) do
                      -- request_handle:logInfo("extract dynamicMetadata key: "..key)
                      if(key == "envoy.filters.http.jwt_authn")
                      then
                        if(value.jwt_payload ~= nil and value.jwt_payload.permissions ~= nil)
                        then
                          -- request_handle:logInfo("value.jwt_payload.permissions is not null")
                          for k, v in pairs(value.jwt_payload.permissions) do
                            -- request_handle:logInfo("permission: "..v)
                            if(v == 'read:service')
                            then
                              -- request_handle:logInfo("return")
                              return
                            end
                          end
                        end
                        request_handle:respond({[":status"] = "403",},"JWT validation failed.") 
                      end
                    end
                  end
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: upstream-service
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: upstream-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: upstream-service
                port_value: 8080

  - name: take0a.jp.auth0.com|443
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: take0a.jp.auth0.com|443
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: take0a.jp.auth0.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: take0a.jp.auth0.com
